FROM node:18-alpine AS prod

RUN npm i -g npm@latest

ARG NODE_ENV=production

ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install --only=production

RUN rm -f package.json